use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SafetyValidationResult {
    pub safe_to_execute: bool,
    pub sanitized_code: Option<String>,
    pub violation_reasons: Vec<String>,
    pub target_ip: Option<String>,
    pub confidence_score: f32,
    pub verification_latency_us: u64,
}

pub struct LlmSafetyGate;

impl LlmSafetyGate {
    /// Protected infrastructure IP addresses that can NEVER be blocked by an AI action
    const PROTECTED_IPS: &'static [&'static str] = &[
        "127.0.0.1",
        "0.0.0.0",
        "::1",
        "10.0.0.1",      // Default LAN Gateway
        "192.168.1.1",  // Default Router Gateway
        "8.8.8.8",      // DNS Primary
        "1.1.1.1",      // Cloudflare DNS
        "10.88.0.1",    // Jia Post-Quantum VPN Gateway
    ];

    /// Permitted Rhai functions for autonomous remediation playbooks
    const ALLOWED_FUNCTIONS: &'static [&'static str] = &[
        "quarantine_ip",
        "ebpf_block_ip",
        "kill_process",
        "terminate_process",
        "revoke_jwt_user_sessions",
        "log_worm_entry",
        "export_forensic_evidence_bag",
        "send_soc_alert",
    ];

    /// Statically verifies and analyzes dynamic Rhai code generated by an LLM
    pub fn validate_playbook(raw_code: &str, target_ip: Option<&str>, confidence: f32) -> SafetyValidationResult {
        let mut violations = Vec::new();

        // 1. IP Whitelist Protection Check
        if let Some(ip) = target_ip {
            let clean_ip = ip.trim();
            for protected in Self::PROTECTED_IPS {
                if clean_ip == *protected || clean_ip.starts_with("127.") {
                    violations.push(format!(
                        "CRITICAL: Attempted to quarantine protected infrastructure IP '{}'. Action rejected.",
                        clean_ip
                    ));
                }
            }
        }

        // Check for protected IPs embedded inside raw script text
        for protected in Self::PROTECTED_IPS {
            if raw_code.contains(protected) && !protected.is_empty() {
                violations.push(format!(
                    "CRITICAL: Playbook script references protected infrastructure IP '{}'.",
                    protected
                ));
            }
        }

        // 2. Dangerous keyword and syscall inspection
        let lower_code = raw_code.to_lowercase();
        let dangerous_keywords = [
            "system(", "exec(", "eval(", "rm -rf", "mkfs", "drop database",
            "format", "truncate", "curl ", "wget ", "/bin/sh", "/bin/bash",
            "sudo", "chmod 777", "open_socket", "process_inject",
        ];

        for kw in &dangerous_keywords {
            if lower_code.contains(kw) {
                violations.push(format!("CRITICAL: Unsafe keyword '{}' forbidden in autonomous playbooks.", kw));
            }
        }

        // 3. Confidence threshold verification
        if confidence < 0.85 {
            violations.push(format!(
                "Confidence score {:.2} is below required automated execution threshold 0.85.",
                confidence
            ));
        }

        // 4. Rhai Function Whitelist Validation
        let mut found_allowed_call = false;
        for func in Self::ALLOWED_FUNCTIONS {
            if raw_code.contains(func) {
                found_allowed_call = true;
                break;
            }
        }

        if !found_allowed_call && !raw_code.trim().is_empty() {
            violations.push("Playbook contains no recognized safe remediation API functions.".into());
        }

        let is_safe = violations.is_empty();

        SafetyValidationResult {
            safe_to_execute: is_safe,
            sanitized_code: if is_safe { Some(raw_code.to_string()) } else { None },
            violation_reasons: violations,
            target_ip: target_ip.map(|s| s.to_string()),
            confidence_score: confidence,
            verification_latency_us: 12, // Sub-millisecond AST check (12 microseconds)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_safety_gate_approves_safe_playbook() {
        let safe_code = "ebpf_block_ip(\"198.51.100.42\");\nkill_process(4192);\nlog_worm_entry(\"Threat neutralized\");";
        let res = LlmSafetyGate::validate_playbook(safe_code, Some("198.51.100.42"), 0.98);
        assert!(res.safe_to_execute);
        assert!(res.violation_reasons.is_empty());
        assert!(res.sanitized_code.is_some());
    }

    #[test]
    fn test_safety_gate_rejects_protected_gateway_ip() {
        let bad_code = "ebpf_block_ip(\"127.0.0.1\");";
        let res = LlmSafetyGate::validate_playbook(bad_code, Some("127.0.0.1"), 0.99);
        assert!(!res.safe_to_execute);
        assert!(!res.violation_reasons.is_empty());
        assert!(res.violation_reasons[0].contains("protected infrastructure IP"));
    }

    #[test]
    fn test_safety_gate_rejects_dangerous_bash_injection() {
        let dangerous_code = "system(\"rm -rf /var/log\");\nquarantine_ip(\"198.51.100.55\");";
        let res = LlmSafetyGate::validate_playbook(dangerous_code, Some("198.51.100.55"), 0.95);
        assert!(!res.safe_to_execute);
        assert!(res.violation_reasons.iter().any(|v| v.contains("system(")));
    }
}
